LICENSE
package.json

- License is `Apache-2.0`
- Added the missing `LICENSE` file
- Updated the `license` field on `package.json`
Additionally, updated the `author` and `contributors` information on `package.json`.

Fix license information

---

README.md

The YAML example was 'host'  when it should be called 'schemes'.

Small typo on section 'schemes'

---

README.md

Fixed a typo on the Message spec. 
According to the code and examples tags should be a list of Tag Objects instead a list of strings as documentation was pointing.

Tags are a list of Tag Objects and not a list of strings

---

README.md
schema/asyncapi.json
test/docs/sample.yml
test/docs/sample2.yml
test/docs/test-payload-string.yml
test/index.js

This removes the host and schemes properties. For a better way to declare servers, protocols, etc. we followed the same approach as OpenAPI 3.0.0, using a `servers` object in the top level of the document. As discussed in https://github.com/asyncapi/asyncapi/issues/28.

Add servers object and remove host and schemes properties

---

README.md

Uses the fact that YAML is a superset of JSON, but treats ... as a string literal.

Eliminate red-highlight of [...] in json example

---

schema/asyncapi.json

To me it looks like as is if the `termsOfService` field is missing the URI format.

Mark URL field as format 'uri'

---

README.md
schema/asyncapi.json

It adds support for:
1. Defining security schemes inside the Components object.
2. Specify security requirements to authorize the connection.
As a result of an investigation about ways to protect your API using MQTT, AMQP and WebSockets, I came up with the following list:
1. User/Password: That's the most common when the API is private.
2. API Key (over User/Password): It feels like a hack to me but I've seen it in many places. It consists in sending an API token as the user or as the password when connecting to a system that expects a User/Password. Usually, the other field is left empty. For instance:
```yaml
user: AF89AFDKLK23423NADSFDS89AS79
password: (empty)
```
3. X.509 Certificate: That's very common for internal and/or partnership APIs.
4. End-to-end Encryption: Either symmetric …

Add security schemes and requirements

---

README.md
schema/asyncapi.json

This PR adds support for Kafka. From now on you can also specify `kafka` and `kafka-secure` on a server scheme.
**Example:**
```yaml
servers:
- url: kafka.company.com:9092
description: Company's Kafka broker.
scheme: kafka
```

Add support for Kafka

---

README.md
schema/asyncapi.json

It now allows to specify scheme version in the server object:
```yaml
servers:
- url: api.company.com
scheme: amqp
schemeVersion: '0.9.1'
```
```yaml
servers:
- url: api.company.com
scheme: kafka
schemeVersion: '1.0.0'
```

Add scheme version to server object

---

README.md
schema/asyncapi.json

It now uses [IANA name for secure MQTT](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=secure-mqtt) (`secure-mqtt`) instead of `mqtts`.
The change is backward compatible. The schema still supports `mqtts` but it will be removed on the next major version.

Rename mqtts to secure-mqtt

---

README.md

This aligns the spec. more closely with the wording and formatting of the OASv3 spec.

Formatting changes for RFC2119 key words

---

README.md

...Including in examples.
None of
* commonmark.org
* yaml.org
* jsonschema.org
support https at the present time.

v2; prefer https scheme where applicable

---

README.md
schema/asyncapi.json
test/docs/sample.yml

* Parameter object expanded to include `$ref` property, as per schema etc
* Components object expanded to include `parameters` property
* Schema updated
* Sample doc updated
* Version bumped to 1.2.0 speculatively
* Minor fix to an example to ensure they all parse ok (mdv)
* "Open API Intiative" and "Open API Specification" -> "OpenAPI" as per recent change
Test passes.

Re-usable parameters, fixes #71

---

README.md
schema/asyncapi.json
test/docs/gitter-streaming.yml

This PR adds support for defining streaming APIs.
It introduces a new root-level object called `stream`. It looks like this:
```yaml
stream:
framing:
type: 'chunked'
delimiter: '\r\n'
read:
- $ref: '#/components/messages/chatMessage'
- $ref: '#/components/messages/heartbeat'
```
**From now on, the `topics` object is not required if `stream` is present.**
\cc @jkarneges @MikeRalphson @kinlane

Add support for Streaming APIs

---

README.md
schema/asyncapi.json
test/docs/slack-rtm.yml

This PR adds support for Events APIs, i.e., APIs that don't have topics, e.g., a WebSockets API.
It also contains the Slack RTM API as an example. It doesn't document the whole API though :sweat_smile:
\cc @kinlane @MikeRalphson @jkarneges

Add support for Events APIs

---

README.md

As @derberg correctly pointed out [here](https://github.com/asyncapi/asyncapi/pull/123/files#r254436884), I'm changing the words and the link for past and future meeting agendas.
It was really confusing.

Fix wording and link for meeting agendas

---

.travis.yml
package-lock.json
package.json
test/index.js

I just improved "tests" a little bit. It now runs tests for every document in the examples directory. You can also select which versions you want to run.
Run tests for specific versions:
```bash
npm test -- --versions 1.2.0,next
```
It's very convenient while working on the spec.

Automate testing against all examples

---

examples/next/anyof.yml
examples/next/gitter-streaming.yml
examples/next/not.yml
examples/next/oneof.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Fixes #110 and fixes #111.
It just renames `topics` as `channels` and removes `events`.
* Channels is a much broader term, not tied to specific technologies.
* Since channels are URIs (see #124), the root channel (`/`) will act as a "no channel" or "global channel".

Rename topics to channels and remove events

---

examples/next/gitter-streaming.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Fixes #48 
It makes more sense to have the security requirement as part of the server object since auth mechanisms might change depending on the server.

Move security requirements to server object

---

versions/next/asyncapi.md
versions/next/schema.json

Fixes #91 
Removes the restriction on the `scheme` field, allowing it to contain any string value.
After thinking a lot, I came to the conclusion that restrictions on this field were just causing the tooling to evolve more slowly, and proposed solutions were just making it more complicated for the tools to validate.
We can keep a list of suggested values and make sure the tools follow them. In case this goes wild, nothing stops us from putting the restriction back.

Remove scheme restrictions

---

versions/next/asyncapi.md

Fixes #103 
It doesn't make sense. See #103.

Server Variable Object: Remove statement requiring at least one field

---

examples/next/anyof.yml
examples/next/not.yml
examples/next/oneof.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Prepares the spec for #77 and #54.
It also changes how schema format is defined. Changed from this:
```yaml
channels:
event/{streetlightId}/lighting/measured:
subscribe:
payload:
'application/schema+json;version=draft-07':
$ref: "#/components/schemas/lightMeasuredPayload"
```
to this:
```yaml
channels:
event/{streetlightId}/lighting/measured:
subscribe:
message:
schemaFormat: 'application/schema+json;version=draft-07'
payload:
$ref: "#/components/schemas/lightMeasuredPayload"
```
We need to accommodate the spec to do things like the following:
```yaml
channels:
event/{streetlightId}/lighting/measured:
subscribe:
operationId: receiveLightMeasure
contentType: 'application/json'
message:
schemaFormat: 'application/schema+json;version=draft-07'
payload:
$ref: …
```

Separate operation from message and change schema format definition mechanism

---

versions/next/asyncapi.md

I forgot to add `schemaFormat` to the human-readable specification. This PR adds it.

Add schema format to markdown spec

---

examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Fixes #79 
When a message is referenced, it's impossible for a tool (e.g., documentation renderer) to know the name of the message. Example:
```yaml
publish:
$ref: '#/components/messages/myMessage'
components:
messages:
myMessage:
payload:
type: object
properties:
...
```
The example above results in the following after resolving `$ref`s:
```yaml
publish:
payload:
type: object
properties:
...
```
As you can see, the name `myMessage` is lost. That's why we need `name` and `title` (a more human-friendly version of the name).

Add name and title to message object

---

examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Fixes #54 
See #54 
We can infer the content type in most cases from the schema definition. For instance, if it's defined using JSON Schema we can consider the content type of the payload is JSON. If the schema format is XSD, we know it's XML. However, some schema formats allow for other types of encoding, like Protobuf, which supports sending the message as binary or as JSON.

Add contentType property to message object

---

examples/next/correlation-id.yml
versions/next/asyncapi.md
versions/next/schema.json

Fixes #78 
As follows:
* Added Correlation ID object
* Added runtime expression support
* Added Correlation ID Map to Components Object
* Added Correlation ID to Message Object
* Updated schema and added example to test
A couple of bits of food for thought:
* Is the ABNF definition too restrictive?
* Is it right to match the ABNF definition in schema?
* **Would welcome suggestions as to whether more references are needed anywhere else in the specification as it stands i.e. defining a Correlation ID at a higher level than Message**

Issue #78 addition of Correlation ID to specification

---

examples/next/application-headers.yml
versions/next/asyncapi.md
versions/next/schema.json

Summary of changes:
* Changed the `headers` property from a Schema Object to a Map of Schema or Reference Objects
* Changed wording on `headers` property to constrain it to applications headers i.e. it does not include protocol headers, which will be defined by #42 
* Updated examples of headers throughout
* Changed JSON Schema and used `patternProperties` to define the map and constraints on types.
* Provided an example for testing.

Issue #112 change scope of Message Object headers to application headers only

---

versions/next/schema.json

Makes use of a reusable `ReferenceObject` object.
So we easily identify where we can use `$ref`s in the specification and also to embrace reusability.

Clean $refs in schema

---

versions/next/asyncapi.md
versions/next/schema.json

* Rename message's `example` field to `examples`.
* Add `examples` field to the schema object.
Fixes #172 
To make it uniform across the spec. In the case of the schema object, we don't remove the existing `example` field to remain compatible with OpenAPI schemas.

Unify examples fields

---

examples/next/gitter-streaming.yml
versions/next/asyncapi.md
versions/next/schema.json

Removes the `stream` object from the root of the document. From now on, everything can be defined using `channels`.
> Please, note that it doesn't mean we're not going to support HTTP streaming anymore. On the contrary, we're cleaning the syntax for better growth. See `gitter-streaming` example to get an idea of how it will look like.
This is part of the strategy to unify everything in channels.

Remove stream object

---

examples/next/application-headers.yml
examples/next/correlation-id.yml
examples/next/gitter-streaming.yml
examples/next/rpc-client.yml
examples/next/rpc-server.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Use `protocol` instead of `scheme` in the server object.
It's creating confusion with:
1. Security schemes.
2. Schemas.
Thanks, @jschabowsky for the suggestion.

Rename scheme as protocol

---

examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

This introduces a 'description' for the channel item object as discussed in #207

Adding a description for the channel item object

---

versions/next/asyncapi.md

I noticed that the formatting of this section of properties was incorrect on the asyncapi web site (but fine when viewed in GitHub).  I assume this change will fix the problem, but I can't verify since I don't know how the website is displaying the MD.
Here is how it currently looks when rendered on the web site:
This is definitely one of my better open source contributions.  ;)
Signed-off-by: Eric Wittmann <eric.wittmann@gmail.com>

Fixed a formatting issue with a bullet list of schema properties.

---

versions/next/asyncapi.md

The data type of `traits` field in https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#componentsObject is not syntactically correct. I assume it should be `Map[string, Operation Trait Object | Message Trait Object]`.

Fix typo in Components Object/traits data type

---

versions/next/asyncapi.md

Fixes #216 
Props to @jstoiko.

Remove support for non-JSON schemas (i.e. Protobuf, XSD, etc.)

---

examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

* Simplify traits by not allowing variable replacement.
* Separate traits in `messageTraits` and `operationTraits` in components as they are different object types.

Simplify traits

---

examples/next/application-headers.yml
examples/next/correlation-id.yml
examples/next/gitter-streaming.yml
examples/next/rpc-client.yml
examples/next/rpc-server.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Changes:
* Makes parameters a map instead of an array. This way we always make sure a name is provided.
* Makes servers a map instead of an array. It gives us the advantage of assigning names to each server, e.g. production, development, staging, etc.
The reason behind this change is to facilitate the #107 and #108 features. These features make use of JSON Merge Patch and arrays are particularly "problematic" when trying to merge 2 or more. In the case of JSON Merge Patch, 2 arrays can't be merged and instead the second replaces the first one. If we remove unnecessary arrays from the spec, it will be possible to merge these objects too.

Use maps instead of arrays when possible

---

versions/next/asyncapi.md
versions/next/schema.json

Fixes #212 
@philsturgeon would you mind having a look at this PR? I took yours and changed/added some stuff.
Clarifications:
* XML Object and `xml` property have been removed. Future versions of AsyncAPI will support XSD, which is better suited for XML definitions.
* We're not moving to Draft-08 yet because of the lack of tooling and, IIRC, Draft-08 is still not released. However, we're doing steps in this direction by adding `deprecated` to our superset. Once Draft-08 is out and tooling implemented it, we can get rid of this property.
* We still support OpenAPI schemas on message payloads. Just indicate `schemaFormat` is `application/vnd.oai.openapi;version=3.0.0`. Actually, [once OpenAPI gets rid of their current Schema object](https://github.com/OAI/OpenAPI-Specification/pull/1977) …

Make Schema a superset of JSON Schema Draft 07

---

examples/next/anyof.yml
examples/next/application-headers.yml
examples/next/correlation-id.yml
examples/next/gitter-streaming.yml
examples/next/not.yml
examples/next/oneof.yml
examples/next/rpc-client.yml
examples/next/rpc-server.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

@asyncapi/core-team 
@asyncapi/kyma-team 
Hey folks! I'm releasing version 2.0.0-rc2 which is the one that most probably will become the final version 2.0.0. Next steps are:

Release version 2.0.0-rc2

---

examples/next/application-headers.yml
examples/next/correlation-id.yml
examples/next/rpc-client.yml
examples/next/rpc-server.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md

* Changes the meaning of the publish/subscribe verbs as it was in v1.
* Removes the definition of message broker and replaces any reference to it with the word "server" so we don't confuse people using AsyncAPI for non-broker-based topologies.

Fix operation verbs semantics and definitions

---

README.md

Fix link that points to the previously named folder 'next' rather than 2.0.0

Fix link that points to next version

---

versions/2.0.0/asyncapi.md

While reviewing the latest specification text, it seems to me that the type documentation for `bindings` wasn't properly changed in a couple of spots.  If I'm not mistaken, at least.

Fixed type documentation for `bindings` field in two spots

---

versions/2.0.0/asyncapi.md

Hi,
The YAML example is missing the `bindings` section.
Fixes #275

Add missing 'bindings' section

---

versions/2.0.0/asyncapi.md

**[Current](https://www.asyncapi.com/docs/specifications/2.0.0/#schemaComposition)**
> As such, the `discriminator` field MUST be a required field. There are are two ways to define the value of a discriminator for an inheriting instance. - Use the schema’s name. - Override the schema’s name by overriding the property with a new value. If exists, this takes precedence over the schema’s name. As such, inline schema definitions, which do not have a given id, _cannot_ be used in polymorphism.
**Fixed**
> As such, the `discriminator` field MUST be a required field. There are are two ways to define the value of a discriminator for an inheriting instance.
> - Use the schema’s name.
> - Override the schema’s name by overriding the property with a new value. If exists, this takes precedence over …

Fix list formatting

---

versions/2.0.0/asyncapi.md

I'm adding the definition of "binding" (or "protocol binding") and an incorrect piece of text saying that a "binding" can contain topology-related information.
Make clear what is a "binding". We had definitions for what channel bindings, operation bindings, message bindings, and server bindings must be. However, we didn't have a definition of "binding" itself and it was leading to multiple interpretations.
Bindings are one of the most exciting features of AsyncAPI. It lets you dig down to the specifics of each protocol without polluting the core spec. That said, bindings are also one of the most dangerous features in terms of spec evolution. We don't want bindings to become a black box where anyone can put whatever they want, from topology information to infrastructure/deployment details. …

Add bindings definition

---

documents/git-workflow.md

This PR in a result of a discussion from https://github.com/asyncapi/asyncapi/issues/312 and the SIG open meeting.
Git workflow doc explains that we all (maintainers too) work on forks and how to setup fork to work like a boss so existing maintainers can quickly get into the flow.
I also created a script for setting up a fork, as an alternative to manual steps. Created document links here - https://gist.github.com/derberg/87319e9c486e4a6c9bef5b629ab0d386
Document heavily inspired by the awesome work of Kyma's technical writers - https://kyma-project.io/community/contributing#git-workflow-git-workflow

Add git workflow document

---

.github/workflows/welcome-first-time-contrib.yml
documents/repository-settings.md

Final fix for #314 to document what workflows we should have in each repo

Add info in repo settings instruction about what basic workflows we need

---

examples/2.0.0/mercure.yml
versions/2.0.0/asyncapi.md
versions/2.0.0/schema.json

Hi,
This PR adds support for Mercure, a protocol for async and real-time HTTP APIs.
More info about the protocol:
* https://datatracker.ietf.org/doc/draft-dunglas-mercure/
* https://mercure.rocks

Add support for the Mercure protocol

---

versions/2.0.0/asyncapi.md

`MessageObject` message can be `MessageObject`, `ReferenceObject`
Fixes https://github.com/asyncapi/asyncapi/issues/386

[Specification missmatch]: OperationObject.message

---

versions/2.0.0/asyncapi.md

`MessageObject`, `OperationObject` traits can be `*TraitObject`, `ReferenceObject`
Fixes https://github.com/asyncapi/asyncapi/issues/385

[Specification missmatch]: MessageObject.traits, OperationObject.traits

---

versions/2.0.0/schema.json

- According to specification message headers must be defined as a schema of an object. Other types are not allowed.
- Solution based on https://json-schema.org/understanding-json-schema/reference/combining.html#id5
now validation fails with:
```
"headers": {
"type": "integer",
"enum": [1, 2]
}
```
but it is allowing:
```
"headers": {
"type": "object",
"properties": {
"my-app-header": {
"type": "integer",
"minimum": 0,
"maximum": 100
}
}
}
```
See also https://github.com/asyncapi/parser-js/issues/68
**Comment**
I assume that once this is merged, I also need to create a PR to `asyncapi-node`. See also https://github.com/asyncapi/asyncapi/issues/395

fix: make sure headers must be object type

---

versions/2.0.0/schema.json

- Schema should not enforce minProperties. Schema is not a spec but a tool that helps to work with spec, and should not add rules not described in the spec.
Resolves https://github.com/asyncapi/tck/issues/30

fix: Schema should not enforce minProperties

---

versions/2.0.0/asyncapi.md

- List of scopes can be empty for oauth2 and openIdConnect
See also https://github.com/asyncapi/tck/issues/22#issuecomment-671407523

fix: List of scopes can be empty for oauth2 and openIdConnect

---

versions/2.0.0/asyncapi.md
versions/2.0.0/schema.json

Now examples facet for Message & Message Trait objects are an array of any
Fixes #410

Change examples structure

---

versions/2.0.0/asyncapi.md
versions/2.0.0/schema.json

Reverts asyncapi/asyncapi#436
@BlockLucas Sorry man, I messed it up the other day. The spec was correct but unclear: https://github.com/asyncapi/html-template/issues/59#issuecomment-695999153.
We should still keep that `Whatever "any" is, it MUST match the type defined on the payload.` but slightly rephrased because it can be `headers` or `payload`. We should also make it clear that the "string" in "[Map[`string`, `any`]]" can actually only be either `headers` or `payload`.

Revert "Change examples structure"

---

.github/workflows/automerge.yml
.github/workflows/sentiment-analysis.yml
.github/workflows/welcome-first-time-contrib.yml

This PR is for: https://github.com/asyncapi/asyncapi/issues/445
_GH Actions PR_
- Added Sentiment Analysis workflow
- `pull_request` changed to `pull_request_target` in `.github/workflows/welcome-first-time-contrib.yml` file
- Added Automerge workflow
Resolves: #445
NPM run test works 100%

Add sentiment analysis and automerge for dependabot

---

versions/2.0.0/schema.json

I briefly created a test action to test this change, but found there are some existing actions that just didn't run in my fork. I'm hoping that automated testing is performed when I open this PR. I don't have a Node environment setup so was intending to use CI to test.
Resolves https://github.com/asyncapi/asyncapi/issues/492

fix: change minItems of oneOf and anyOf to 1

---

versions/2.0.0/asyncapi.md

Along with that improve consistency for referencing object names
inside the document.
Closes #499

docs: extend TOC in spec with all its integral parts

---

versions/2.0.0/asyncapi.md

Explicitly clarify all the places where reference objects may be used. This will make the spec more coherent as currently the reference object is only defined in certain places which leads to confusion.
I do not consider these changes as breaking, as they are simply additions which reflect expected behavior.
Relates to https://github.com/asyncapi/asyncapi/issues/406

fix: clarify use of reference objects in async 2.0.0

---

CONTRIBUTING.md

Updating contribution guide as there is a bug that makes only JS Parser a requirement for introducing changes in the spec. JSON Schema is moved to a separate repo and it also must be updated as JS Parser depends on it. So no other option here, you have to accept this PR @fmvilas 😄

fix: add requirement for updating JSON Schema when contributing

---

examples/2.0.0/websocket-gemini.yml

adding a missing websocket example that many people ask for
preview here: https://playground.asyncapi.io/?url=https://raw.githubusercontent.com/derberg/asyncapi/add-websocket-example/examples/2.0.0/websocket-gemini.yml

docs: add example for websocket with bindings

---

examples/2.0.0/websocket-gemini.yml

many people go to check out the example of gemini websocket API, good to have references there to more learning materials since we are waiting with Docs for a tech writer.
below is a screen shot info from GitHub Insights, 36 people checked out the example in last 7days

docs: add references to learning materials to websocket example

---

.github/workflows/.releaserc
.github/workflows/release.yml
.releaserc

This PR introduces release automation for the spec using conventional commits spec and following the release cadence agreement.
assumptions:
- all changes for release happen in release branch and every change in release branch produces a prerelease
- merge from release into master branch triggers normal release, like minor or major
- it is possible to merge from just a fork with for example `fix` PR and trigger patch release
See also: https://github.com/asyncapi/spec/issues/536
---
Commit like `fix: spelling mistake in Operations object description` to master branch
Results in a patch release (base was 2.0.1):
Commit like `feat: add something new in some non-release branch` added to branch that doesn't't follow pattern with `-release` suffx
did not trigger a release
Commit like `feat: add …

chore: add release pipeline for the spec

---

spec/asyncapi.md

As discussed in https://github.com/asyncapi/bindings/pull/56 this
adds additional security scheme types. The motivation for adding
them is to enable description of secured Kafka clusters, however
the security protocols and mechanisms being added are not unique
to Kafka, so this commit adds them as generic security schemes so
they could be used by other protocols as well.
Fixes #466

feat: add SASL security scheme types for use by Kafka specs

---

examples/2.1.0/streetlights-kafka.yml
examples/2.1.0/streetlights-mqtt.yml

Main motivation of this was to provide a place to demonstrate
the new Kafka-specific security schemes introduced in
AsyncAPI 2.1.0. It was also a chance to remove the Kafka
bindings from the otherwise-MQTT sample.
The need for this was discussed in
https://github.com/asyncapi/spec/pull/502
Contributes to: #466

docs: separate streetlight examples for Kafka and MQTT

---

README.md
assets/gemini.svg

fixing links to examples that I cleaned up in this PR https://github.com/asyncapi/spec/pull/549
missed it in previous PR, sorry

docs: fix links from readme to examples

---

spec/asyncapi.md

---
title: "Mention about true/false JSON Schemas in Schema Object"
---
As Schema Object in spec is defined as superset of the [JSON Schema Specification Draft 07](http://json-schema.org/), it would be nice to specify that the Schema Object itself can be boolean value. I know it results from the definition of draft 07, so I'd like to hear your opinion about the changes.
Description for `true/false` schemas I took from https://github.com/OAI/OpenAPI-Specification/pull/2609/files Thanks to @MikeRalphson 
> NOTE: PR is a copy of https://github.com/asyncapi/spec/pull/550 but with changed base branch from `master` to `2021-06-release` - remote git see other revisions than I have in local and tries to interpolate the commits from `master` branch 
--- …

fix: clarify support for Boolean JSON Schemas

---

spec/asyncapi.md

According to specification no `name` field exists within Parameter Object.

docs(spec): remove unknown key-value pair

---

spec/asyncapi.md

Added protocol constant that was defined in
https://github.com/asyncapi/bindings/pull/52
Contributes to: asyncapi/bindings#48

feat: add new protocol bindings for IBM MQ

---

.github/workflows/new-spec-release.yml

---
title: "Add step to remove Table of Contents from Spec file"
---
The spec file contains `Table Of Contents`, which would be good to strip out from the website. This action step will remove the TOC from the spec file.

ci: add step to remove toc from spec in action

---

.github/workflows/new-spec-release.yml

---
title: "delete step that removes the `# AsyncAPI Specification` heading"
---
Now that the presence of `# AsyncAPI Specification` in the spec file does not break the website(ref: https://github.com/asyncapi/website/pull/287), it's safe to remove the step which removes that heading.

chore: delete step that removes the `# AsyncAPI Specification` heading

---

examples/streetlights-kafka.yml

Update the Kafka streetlights example so that it uses channel
names that use characters that are valid for use in Kafka topic
names.

chore: update topic names in Kafka example

---

README.md
documents/review/EXAMPLE.md
documents/review/TEMPLATE.md
examples/anyof.yml
examples/application-headers.yml
examples/correlation-id.yml
examples/gitter-streaming.yml
examples/mercure.yml
examples/not.yml
examples/oneof.yml
examples/rpc-client.yml
examples/rpc-server.yml
examples/simple.yml
examples/slack-rtm.yml
examples/websocket-gemini.yml
spec/asyncapi.md

As in title:
- Update the specs version from `2.0.0` to `2.1.0`. 
- Update another occurrences of `2.0.0`. 
- Update Readme.md with link to latest version of spec - https://github.com/asyncapi/spec/blob/2.1.0/spec/asyncapi.md

docs: update specs version to the 2.1.0

---

.github/scripts/remove-toc.js
.github/workflows/new-spec-release.yml
.github/workflows/update-spec.yaml

Add `update-spec.yaml` workflow which will push changes of spec from master branch to the website repo.
Related PR(s)
https://github.com/asyncapi/spec/pull/589

ci: add workflow for updating latest spec doc in the website

---

spec/asyncapi.md

Reading the old issues, I checked that https://github.com/asyncapi/spec/issues/371 issue is still unresolved, so this PR fixes it.
Changes:
- document missed server variable (`{basePath}`) in the example.
Related issue(s)
Resolves https://github.com/asyncapi/spec/issues/371

docs: document missed server variable in the example

---

spec/asyncapi.md

Per documentation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas
JSON specification does not allow trailing commas
On related note the [Components Object Example (JSON)](https://github.com/asyncapi/spec/blob/v2.1.0/spec/asyncapi.md#components-object-example) is ambiguous, because as it currently is, it is not valid JSON object but only part of the object.
Where we have 2 possible resolutions
1. Remove the `"components": ` part to show only the object containing the "Components Object"
2. Wrap the example in another object, possibly just add the opening and closing curly brackets.
All other JSON objects currently in spec are valid afaict

docs: remove trailing commas from examples

---

spec/asyncapi.md

HTTP protocol is discouraged and all domains currently used in spec allow for secure version
Per my simple check, these are the domains (and their usage count) in current spec, so the manual verification of HTTPS support on all of these is trivial
```
> grep -i http spec/asyncapi.md | sed -rn 's@^.*\[(.*)\]\((.*)/.*$@\2@p' | awk -F'/' '{print $3}' | sort | uniq -c | sort -hr
62 github.com
14 tools.ietf.org
14 spec.commonmark.org
3 json-schema.org
2 xml2rfc.ietf.org
2 www.yaml.org
1 www.ietf.org
1 www.ecma-international.org
1 www.apache.org
1 avro.apache.org
```

docs: all links should use secure protocol

---

.releaserc
RELEASE_PROCESS.md

while merging first feature for 2.2 I realized that it is better to do some initial configurations when release branches are created and not put it on the person that contributes the first feature. Now things are just to complex. I also added missing steps about release branch configuration that still has to be done as wildcards are not supported

chore: update release process with missing steps

---

README.md

[streetlights.yml](https://github.com/asyncapi/spec/blob/master/examples/streetlights.yml) has been moved to [streetlights-mqtt.yml](https://github.com/asyncapi/spec/blob/master/examples/streetlights-mqtt.yml)

docs: fix streetlights example link

---

spec/asyncapi.md

fix: unify Message and MessageTrait examples description

---

README.md
examples/anyof.yml
examples/application-headers.yml
examples/correlation-id.yml
examples/gitter-streaming.yml
examples/mercure.yml
examples/not.yml
examples/oneof.yml
examples/rpc-client.yml
examples/rpc-server.yml
examples/simple.yml
examples/slack-rtm.yml
examples/streetlights-kafka.yml
examples/streetlights-mqtt.yml
examples/websocket-gemini.yml
spec/asyncapi.md

Update places that point to the `2.1.0` version, like examples, AsyncAPI Schema formats, titles etc.
Part of https://github.com/asyncapi/website/pull/324

feat: update points from 2.1.0 version to 2.2.0

---

.github/workflows/new-spec-release.yml

---
title: "Fix workflow to remove multiple pre-release specs"
---
This PR will add the ability to remove multiple-pre-release in case a new pre-release is made.
It works based on this intuition that every pre-release contains `-` after the release version

ci: fix workflow to remove multiple pre-release specs from website

---

CODEOWNERS

I have to admit that my initial CODEOWNER configuration was not the best, like future-proof, especially now for the permissions cleanup

chore: fix codeowners file to enable people to also decide and not just bot :smile:

---

.github/workflows/if-nodejs-release.yml
spec/asyncapi.md

---
title: "Add Solace bindings to the list of supported bindings in the spec."
---
This is a request to add the Solace bindings to the lists of bindings in the spec.
The PR for the json schema repo corresponding to this PR is here: https://github.com/asyncapi/spec-json-schemas/pull/136

feat: add Solace bindings to the list of supported bindings in the spec.

---

examples/social-media/backend/asyncapi.yaml
examples/social-media/common/servers.yaml
examples/social-media/frontend/asyncapi.yaml
spec/asyncapi.md

> Note that this PR is targeting `asyncapi:2022-01-release` branch, so merging it won't release a new version.
This PR is part of https://github.com/asyncapi/spec/issues/660.
It allows both `servers` and `channels` to be defined as (and referenced from) components, meaning the following will be now valid:
```yaml
servers:
production:
$ref: '#/components/servers/myserver'
channels:
some/events:
$ref: '#/components/channels/myChannel'
components:
servers:
myserver:
url: "http://localhost:5000/ws"
protocol: ws
channels:
myChannel:
description: "mychannel"
```
https://github.com/asyncapi/spec/issues/660

feat: allow servers and channels to be defined as components

---

spec/asyncapi.md

---
title: "Change version to 2.3.0"
---
Noticed there were still references to 2.2.0 in the spec docs, updated them to 2.3.0
---
---

docs: change version to 2.3.0

---

README.md

I've noticed that the version list in main README file is missing 2.3.0 version of the spec. This PR provides remediation.

chore: add 2.3.0 version to the list in readme

---

spec/asyncapi.md

---
title: "fix example typo"
---
Fix a typo on the "Channel Item Object Example" YAML example in the specification file.

docs: fix example typo

---

.releaserc

In order to allow CI to release pre-releases for `2022-04-release`, we need to merge this into `master` branch.
Part of https://github.com/asyncapi/spec/issues/735

chore: add 2022-04-release branch in .releaserc

---

RELEASE_PROCESS.md

As @derberg caught in https://github.com/asyncapi/spec/pull/741/files#r833327198, we should also add a reference to the latest spec version in the `README.md` during the release process.
https://github.com/asyncapi/spec/pull/741/files#r833327198

docs: add a new release step to RELEASE_PROCESS.md

---

RELEASE_PROCESS.md

Since the latest updates on the bots, the behaviour for autoupdating a branch with upstream changes has changed.
Now, it is based on the label `autoupdate`, which can be added by `/au` command. This step is crucial for the release process.

docs: autoupdate label step for RELEASE_PROCESS.md

---

spec/asyncapi.md

---
title: "add server definition in spec"
---
Let's [add a 'server' definition in our Spec under the Definitions section](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#definitions)
---
Resolves website issue [#587](https://github.com/asyncapi/website/issues/587)

docs: add server definition in spec

---

spec/asyncapi.md

---
title: "Server Variable Object as reusable object"
---
---
#707 
---
The PR targets to have Server Variable Objects as reusable objects within the Component Object.

feat: added server variable object as reusable object

---

spec/asyncapi.md

---
title: "add messageId property"
---
---
closes #458 
---

feat: add messageId property

---

.github/scripts/remove-toc.js
.github/workflows/new-spec-release.yml
.github/workflows/update-spec.yaml
CODE_OF_CONDUCT.md

---
title: "updating spec urls to match new Information Architecture changes via https://github.com/asyncapi/website/pull/601"
---
301 updates due to GSoD IA changes
---
https://github.com/asyncapi/website/pull/601/ 
---

ci: updating spec urls to match new Information Architecture in website

---

README.md
examples/anyof.yml
examples/application-headers.yml
examples/correlation-id.yml
examples/gitter-streaming.yml
examples/mercure.yml
examples/not.yml
examples/oneof.yml
examples/operation-security.yml
examples/rpc-client.yml
examples/rpc-server.yml
examples/simple.yml
examples/slack-rtm.yml
examples/streetlights-kafka.yml
examples/streetlights-mqtt.yml
examples/streetlights-operation-security.yml
examples/websocket-gemini.yml
spec/asyncapi.md

This PR sets all references from `2.4.0` to `2.5.0`, including examples.

chore: set 2.5.0 as the latest version of the spec

---

spec/asyncapi.md

Some fixed fields description have dots and some don't. This PR provides remediation and introduces a little bit more consistency.

docs: end OAuth Flows Object field descriptions always with dot

---

spec/asyncapi.md

This is an editorial change, so sending against `master` branch.
Refs https://github.com/swagger-api/apidom/issues/1663
More on RFC 2119 -> https://www.rfc-editor.org/rfc/rfc2119

docs: align wording with RFC 2119

---

examples/streetlights-kafka.yml

---
YAML Formatting problem in Kafka Streetlights example
---
Title says it all. :)

docs: fix incorrect spacing in the kafka streetlights example

---

spec/asyncapi.md

https://xml2rfc.ietf.org/public/rfc/html/rfc3339.html now returns 404. This PR replaces the no longer valid link for another equivalent one: https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6
Refs #831

docs: change invalid RFC3339 link for valid one

---

.github/ISSUE_TEMPLATE/release.md
.github/workflows/link-check-cron.yml
.github/workflows/stale-issues-prs.yml
LICENSE
NOTICE
README.md
examples/streetlights-kafka.yml
spec/asyncapi.md

This is PR is part of https://github.com/asyncapi/spec/issues/830 and updates `next-spec` branch with changes from `master`.

chore: update next-spec branch with master changes

---

.github/workflows/release.yml

when we changed release branches, we forgot to update the workflow that reacts to them, we forgot to change the names of branches in the config
I intentionally did not make a change like `'**-spec'` to have branches named explicitly

ci: fix release workflow to support release branches

---

examples/social-media/backend/asyncapi.yaml
examples/social-media/comments-service/asyncapi.yaml
examples/social-media/notification-service/asyncapi.yaml
examples/social-media/public-api/asyncapi.yaml
examples/streetlights-kafka.yml
examples/streetlights-mqtt.yml
spec/asyncapi.md

This PR adds support for defining Tags at Server Object. They can be used for providing metadata, including the environment such as `production`, `development`, etc.
Fixes https://github.com/asyncapi/spec/issues/654
Fixes https://github.com/asyncapi/spec/issues/465

feat: add tags field to Server Object

---

spec/asyncapi.md

I found that we have forgot to define (probably it's a bug) definition for `IBM MQ Operation Binding`. I know that some bindings don't need to have definition for particular kind of binding, but we should have reserved keywords.
I found it in review of https://github.com/asyncapi/spec/pull/836 PR 
cc @derberg @fmvilas and @dalelane you should be most interested :)

fix: add missed IBM MQ Operation Binding

---

spec/asyncapi.md

---
title: "Move operations to its own root object"
---
---
#618 #663
---

feat!: move operations to its own root object

---

spec/asyncapi.md

Adds support for Google Cloud Pub/Sub to the `Channel Binding Object` and `Message Binding Object` lists.
Bindings PR: https://github.com/asyncapi/bindings/pull/141
JSON Schema PR: https://github.com/asyncapi/spec-json-schemas/pull/253

feat: add googlepubsub bindings

---

CODEOWNERS
CONTRIBUTING.md

Closes #844 
Closes #845 
https://github.com/asyncapi/spec-json-schemas/pull/271

chore: add Sergio and Vladimir as code owners

---

spec/asyncapi.md

This fixes the inconsistent title level for definitions and specification.

chore: fix inconsistent title level

---

spec/asyncapi.md

---
title: "remove action and channel fields from Operation Trait Object"
---
---
https://github.com/asyncapi/spec/issues/856
---
This PR only shows what changes should be done described in the mentioned issue (https://github.com/asyncapi/spec/issues/856). If we decide to leave these fields, I will close the PR.
I think the ability to define `channel` and `action` at the trait level is bad, because both fields are required by the operation itself.

fix: remove action and channel fields from Operation Trait Object

---

.gitignore
examples/operation-security.yml

`security` property on operation level is supposed to be an array of security requirement objects and not a single object -> https://www.asyncapi.com/docs/reference/specification/v2.5.0#operationObject
example before fix: https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/spec/master/examples/operation-security.yml
example after fix: https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/derberg/asyncapi/c61b29329b73867f98914c607f03015549169c34/examples/operation-security.yml

chore: fix example for operation security

---

spec/asyncapi.md

This PR changes the AsyncAPI version to 3.0.0.
I can't remember, was it in the spec that we did not want to change this for now @derberg? Because it would be creating breaking changes when we do version 2.6? (if we do)

chore: update AsyncAPI version to 3.0.0

---

examples/social-media/backend/asyncapi.yaml
examples/social-media/comments-service/asyncapi.yaml
examples/social-media/frontend/asyncapi.yaml
examples/social-media/notification-service/asyncapi.yaml
examples/social-media/public-api/asyncapi.yaml

---
title: "chore: update asyncapi versions in the social-media example"
---
I wanted to test some spec (that is somewhere on the web) with refs to the files and I noticed that the `social-media` example points to old version of AsyncAPI.

chore: update asyncapi versions in the social-media example

---

spec/asyncapi.md

This PR unifies all the referencing mechanisms in the spec. So far, only the `security` requirements object had to be changed.
#829

feat: unify all referencing mechanisms

---

.github/workflows/add-good-first-issue-labels.yml
.github/workflows/scripts/mailchimp/package-lock.json

updated release branch 
cc @derberg

chore: update release branch

---

.github/workflows/add-good-first-issue-labels.yml

https://github.com/asyncapi/spec/pull/903 did not work as expected

chore: another update of release branch

---

spec/asyncapi.md

---
title: "use union for operation action"
---
Use union to describe available values for operation's `action` field.

fix: use union for operation action

---

spec/asyncapi.md

feat: replace server url with server host and pathname

---

.github/workflows/update-spec.yaml

[This CI run](https://github.com/asyncapi/spec/actions/runs/4594476058/jobs/8113554780) overwrote spec document from release candidate, in the website.
The action that we used to check the spec version that should be updated, did not take into consideration pre-releases, and instead of getting from API latest release as `2.6` it fetched the last release candidate
Upgraded the workflow to use the latest version of the action that we use, that is fixed and fetch latest release, not pre-releases. I'm not using version number but commit as it is the most recommended and secure way to use non official actions that we do not control

ci: fix spec update in website workflow

---

spec/asyncapi.md

---
title: "Fixes Operation Object link pointing to Channel Object doc"
---
---
- https://github.com/asyncapi/website/issues/1579#issuecomment-1520510317
---

docs: fixes Operation Object link pointing to Channel Object doc

---

spec/asyncapi.md

Following our conversations in the Spec 3.0 meetings, here's the simplification of the Parameter Object.
Fixes #583

feat: simplify parameter object

---

spec/asyncapi.md

small stuff that we forgot, just noticed today when I was explaining req/rep to one of content contributors

docs: add info that runtime expression is used by reply obj

---

.github/workflows/release.yml

---
title: "Update the release workflow on the release branch (next-major-spec)"
---
---
Fixes https://github.com/asyncapi/spec/issues/938
---

ci: update release workflow on release branch

---

.github/workflows/release.yml

Just noticed we had no release candidate since May 30 -> https://github.com/asyncapi/spec/releases/tag/v3.0.0-next-major-spec.12

fix: trigger release with fixed release workflow

---

spec/asyncapi.md

This PR fixes one example I found was out of date.
As a side note, It would be nice if all examples within the spec (not the ones in examples dir) are tested by CI. For that, we would need to include full examples (with all the required fields, such as `info`, etc). https://github.com/asyncapi/spec/issues/957 might be the issue to push for.

fix: update some examples according to v3

---

spec/asyncapi.md

feat!: remove messageId from Message and MessageTraits objects

---

spec/asyncapi.md

---
title: "Use URL pointing to JSON Schema Draft 7 specs"
---
Adds proper URL to JSON Schema Draft 7. I've used URL that is already used in different part of the AsyncAPI spec for consistency. 
> NOTE: this PR is an editorial change

docs: use URL pointing to JSON Schema Draft 7 specs

---

spec/asyncapi.md

---
title: "Align text definition of Message.payload with it's field definition"
---
> NOTE: this is an editorial change
---
- #928
---

docs: align text definition of Message.payload with it's field definition

---

spec/asyncapi.md

The original spec text seems to inaccurately suggest that multiple AsyncAPI documents are required for each application, whereas the correct statement would be that a single AsyncAPI document, potentially referencing other files, is typically used to describe an application's API.
Perhaps it is more accurate to say that the AsyncAPI Specification defines a set of fields that can be used in one or more AsyncAPI documents to describe an application's API. A single AsyncAPI document can reference other files, but it doesn't mean that multiple AsyncAPI documents are required for a single application.
While the AsyncAPI document is the primary file describing the API, it can include references to other files that contain additional details or shared fields. This doesn't equate to requiring …

docs: update asyncapi document definition

---

spec/asyncapi.md

---
title: "FIX: operation trait object description"
---
---
| Earlier                                                                                                                                   | Now                                                                                               |
| ----------------------------------------------------------------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------ |
| the description didn't exclude the `messages` field as `operation trait object` doesn't have `messages` field like `action` or `channel`. | the exclusion list includes the `messages` field as well along with others.                       |
| …

docs: operation trait object description

---

README.md

---
title: "docs: add missing reference to Version 3.0.0 in README"
---
Add a reference to v3 in the main README. The current README showed v2.6.0 as the latest version.
---
---

docs: add missing reference to Version 3.0.0 in README

---

examples/adeo-kafka-request-reply-asyncapi.yml

Replace `example` with `examples`
Reference: https://github.com/asyncapi/spec/issues/1031

docs: fix adeo-kafka-request-reply-asyncapi.yml

---

spec/asyncapi.md

Replace Specification Extensions Field Pattern - `^x-[\w\d\-\_]+$` with `Field Pattern`^x-[\w\d\.\x2d_]+$`
Reference: https://github.com/asyncapi/spec/issues/1031

docs: fix Specification Extensions Field Pattern

---

spec/asyncapi.md

This pull request includes a small change to the `spec/asyncapi.md` file. The change adds information about the possibility of extending the server object with specification extensions.
* [`spec/asyncapi.md`](diffhunk://#diff-34bca0c91901dffce093114c7d4cac16477410fbca7cabf3a1b888d7dfc3eb4dR488-R489): Added a line indicating that the server object may be extended with [Specification Extensions](#specificationExtensions).

docs: add back extension support on Server Object
