asyncapi/spec

.travis.yml
package.json

References #3 - the build [fails currently](https://travis-ci.org/MikeRalphson/asyncapi/builds/233126839) due to these broken links.

Add Travis CI with mdv step

---

README.md

Remove duplicated link anchor

---

.gitignore
.npmignore
index.js
test/index.js

Prepare `asyncapi` NPM package so the schema can be required from Node.js.

Prepare NPM package

---

LICENSE

It has the same legal effects but GH will recognise it and use more user friendly UI for the repo.

Use a Github friendly Apache 2 License

---

README.md

I'm trying to explain what exactly the AsyncAPI definition files describe, so it's not misunderstood. As pointed out by @ignasi35 in https://github.com/asyncapi/asyncapi/issues/15.

Better explanation of what the AsyncAPI document describes

---

README.md

After playing a little bit with the previous description we found out it was not the best way to structure the files.

Recommendations on how to structure files

---

README.md

Will be picked up by mdv v1.0.7

Fix internal link to topicItemObject

---

schema/asyncapi.json

Allows samples to be validated

schema; allow $ref in message object

---

README.md
schema/asyncapi.json
test/docs/sample.yml

Fix terms of service descriptions and examples

---

README.md
schema/asyncapi.json

It fixes #52.
This PR is part of the 1.1.0 release.

Add support for JMS

---

README.md
schema/asyncapi.json
test/docs/sample.yml

It fixes #51.
This PR is part of the 1.1.0 release.

Add support for topic parameters

---

schema/asyncapi.json
test/docs/anyof.yml
test/docs/not.yml
test/docs/oneof.yml
test/docs/sample.yml

Fix asyncapi version

---

CONTRIBUTING.md
package-lock.json
package.json

Added a document explaining how to contribute to the project.
[Let's make AsyncAPI a welcoming community](https://trello.com/c/uCq8ulJa/1-add-contributing-guidelines)

Add contributing guidelines

---

.travis.yml
package.json
versions/1.0.0/asyncapi.md
versions/1.1.0/asyncapi.md

I'm making `npm test` to run "tests" and mdv. Also, I'm limiting mdv to check for versions directory only.
So it doesn't bother on README with all-contributors bot.

Run tests with mdv and apply mdv only to versions directory

---

README.md

Adds information on how to donate and become a sponsor of the project.

Add open collective

---

examples/next/gitter-streaming.yml
versions/next/asyncapi.md
versions/next/schema.json

Add examples to server variable object

---

examples/next/anyof.yml
examples/next/gitter-streaming.yml
examples/next/not.yml
examples/next/oneof.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Fixes #113 
See #113 for the explanation.

Add support for multiple schema formats

---

examples/next/anyof.yml
examples/next/gitter-streaming.yml
examples/next/not.yml
examples/next/oneof.yml
examples/next/slack-rtm.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Add application identifier

---

examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Add operationId field to operation object

---

versions/next/asyncapi.md
versions/next/schema.json

Add multiLevel field to parameters

---

examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Add support for RAML-like traits

---

versions/next/asyncapi.md
versions/next/schema.json

Cleans some redundant or inconsistent information.

Clean spec

---

versions/next/asyncapi.md
versions/next/schema.json

Explains what a level is.
As per @MikeRalphson comment: https://github.com/asyncapi/asyncapi/pull/173#discussion_r268209183

Remove parameter multiLevel flag

---

versions/next/asyncapi.md

The servers field should be an array.

Fixed an issue with the servers field of the AsyncAPI object

---

examples/next/anyof.yml
examples/next/application-headers.yml
examples/next/correlation-id.yml
examples/next/not.yml
examples/next/oneof.yml
versions/next/asyncapi.md
versions/next/schema.json

Make id optional

---

examples/next/application-headers.yml
versions/next/asyncapi.md
versions/next/schema.json

Make headers of schema type again

---

examples/next/application-headers.yml
examples/next/correlation-id.yml
examples/next/streetlights.yml
versions/next/asyncapi.md
versions/next/schema.json

Remove baseChannel and clarify channel naming constraints

---

versions/next/asyncapi.md

Add missing security scheme types

---

versions/next/asyncapi.md
versions/next/schema.json

Fixes #199 
FYI @jschabowsky @jasonmac01

Add parameter location

---

versions/next/asyncapi.md
versions/next/schema.json

Clarify schema format names

---

versions/next/asyncapi.md

Improve spec intro

---

versions/next/asyncapi.md

Fix JSON Schema link in File structure section

---

examples/next/gitter-streaming.yml

Fix Gitter streaming example

---

versions/next/asyncapi.md

Fix Security Requirement Object definition

---

examples/2.0.0/anyof.yml
versions/2.0.0/schema.json

not sure if the strategy is one `.yml` per test case
Depends on #268

add a test for the fix

---

versions/2.0.0/asyncapi.md

Fix server examples

---

versions/2.0.0/asyncapi.md

Add example polymorphism that overrides use of schema name as discriminator value

---

versions/2.0.0/asyncapi.md

Remove free-form from bindings

---

documents/repository-settings.md

We agreed here #312 and on a SIG call that we will follow certain settings in all repos. Now it has to be documented

Add info about what settings we have in all the repositories

---

versions/2.0.0/asyncapi.md

Make Avro and OpenAPI Schemas support recommended instead of mandatory

---

documents/repository-settings.md

- Add info that `Automatically delete head branches` must be selected
- Add info about sponsoring option
See also: #312

Add information to repository setting doc about branch deletion

---

examples/2.0.0/mercure.yml

This PR fixes a bug I introduced in the Mercure example.

Mercure example: externalDocs isn't allowed here

---

README.md

docs: remove broken badge

---

versions/2.0.0/asyncapi.md

add default content type to root schema #407

---

test/index.js

- Just had to remove the _smelly code_ by getting rid of the try catch block. Tests run perfectly showing that the future is bright! :100: 
Fixes #440

Removed try-catch in test's index.js

---

examples/2.0.0/README.md

Remove outdated readme
Fixes #299

Delete not needed README for examples

---

.github/workflows/automerge.yml
.github/workflows/sentiment-analysis.yml

- Fix broken new workflows for sentiment and dependanbot

Fix broken new workflows for sentiment and dependanbot

---

package.json

This PR will be merged and right after it, the global replacement:
- https://github.com/asyncapi/.github/pull/18
- https://github.com/asyncapi/.github/pull/21
See also https://github.com/asyncapi/asyncapi/issues/423

ci: add scritps to package.json that are required by global workflows

---

package-lock.json
package.json

- support testing on windows. With new version of mdv we would have this solved as you can see here https://github.com/asyncapi/asyncapi/pull/495/checks?check_run_id=1823847384
See also https://github.com/asyncapi/asyncapi/pull/493/checks?check_run_id=1817232881

test: support testing on windows

---

.github/workflows/if-nodejs-release.yml
.github/workflows/if-nodejs-version-bump.yml
.github/workflows/release.yml
.releaserc
examples/2.0.0/websocket-gemini.yml

we need changes in release pipeline there in release branch

chore: update release branch with latest master

---

examples/websocket-gemini.yml

as a followup of changes proposed by Laurent

docs: update websocket example with new example props

---

.github/workflows/new-spec-release.yml
.github/workflows/update-spec.yaml

As in title: treat injected value from action context as string.

ci: fix update-spec workflow

---

LICENSE

I'm changing the Copyright to Linux Foundation.

chore: update copyright to LF

---

.releaserc
examples/anyof.yml
examples/application-headers.yml
examples/correlation-id.yml
examples/gitter-streaming.yml
examples/mercure.yml
examples/not.yml
examples/oneof.yml
examples/rpc-client.yml
examples/rpc-server.yml
examples/simple.yml
examples/slack-rtm.yml
examples/streetlights-kafka.yml
examples/streetlights-mqtt.yml
examples/websocket-gemini.yml

- update the version number in examples
- update the release branch name in .releaserc
Contributes to: asyncapi/spec#675

chore: update release branch

---

spec/asyncapi.md

Log that shows breaking build -> https://app.netlify.com/sites/asyncapi-website/deploys/61efc78618da970008ff59a5
Here PR that got merged after fixing `<br>` -> https://github.com/asyncapi/website/pull/567/files#diff-1699deb4ec142d39730ee1c744b0733210d41de3766efd4ec61e5f089a3acad7R517

docs: fix <br> tags that break building asyncapi website

---

spec/asyncapi.md

Noticed wrong version on website when I was reading through AsyncAPI Specification.

docs: fix version in asyncapi.md

---

CODEOWNERS

Add @dalelane as a code owner
Closes #720

chore: add Dale Lane as code owner

---

.releaserc
examples/anyof.yml
examples/application-headers.yml
examples/correlation-id.yml
examples/gitter-streaming.yml
examples/mercure.yml
examples/not.yml
examples/oneof.yml
examples/rpc-client.yml
examples/rpc-server.yml
examples/simple.yml
examples/slack-rtm.yml
examples/streetlights-kafka.yml
examples/streetlights-mqtt.yml
examples/websocket-gemini.yml
spec/asyncapi.md

Part of https://github.com/asyncapi/spec/issues/735

chore: update 2022-04-release branch

---

.github/ISSUE_TEMPLATE/release.md

This PR adds a list of issues/PRs that can be potentially included in the release version. Also, a cleanup tasks list to happen after the release. 
Based on the latest release: https://github.com/asyncapi/spec/issues/735

ci: improve GH ISSUE_TEMPLATE.md

---

spec/asyncapi.md

---
title: "Clarify introduction"
---
---
Fixes #859 
Fixes #538

chore: clarify introduction

---

examples/gitter-streaming-asyncapi.yml

Fixes https://github.com/asyncapi/spec/issues/985

chore: fix gitter binding example 

---

CODEOWNERS

More at https://github.com/asyncapi/community/pull/1906

chore: remove smoya from CODEOWNERS
